# https://dev.azure.com/open-peer-power

trigger:
    batch: true
    branches:
      include:
      - master
  pr:
  - master
  
  
  jobs:
  
  - job: 'JQ'
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
    - script: sudo apt-get install -y jq
      displayName: 'Install JQ'
    - bash: |
        shopt -s globstar
        cat **/*.json | jq '.'
      displayName: 'Run JQ'
  
  
  - job: 'S3'
    condition: and(eq(variables['Build.SourceBranchName'], 'master'), succeeded('JQ'))
    dependsOn: 'JQ'
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
    - task: UsePythonVersion@0
      displayName: 'Install Python 3.7'
      inputs:
        versionSpec: '3.7'
    - script: pip install awscli
      displayName: 'Install aws cli'
    - script: |
        export AWS_ACCESS_KEY_ID="$(aws.AccessKey)"
        export AWS_SECRET_ACCESS_KEY="$(aws.SecretKey)"
  
        aws s3 sync . s3://oppio-version --exclude "*" --include "*.json" --include "*.txt"
        aws s3 sync . s3://version.open-peer-power.io --exclude "*" --include "*.json" --include "*.txt"
      displayName: 'Upload data to s3 oppio-version'