# See options at https://github.com/coogie/oscailte
# ----------------------- #
#      Main Configs       #
# ----------------------- #
title: Open Peer Power
subtitle: Open-source nano-grid power management platform running on Python 3
author: Open Peer Power
simple_search: https://www.google.com/search
email: 
description: >- # this means to ignore newlines until "baseurl:"
  The objective of Open Peer Power is to enable electrical power prosumers - those who both  
  consume and produce electrical power to take control of their own situation.
  Power comes from knowledge, control and cooperation with like minded prosumers.

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://openpeerpower.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:
# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

source: source
destination: public/
# Build settings
markdown: kramdown
timezone: UTC
# Default date format is "ordinal" (resulting in "July 21st 2018")
# The format as defined in http://www.ruby-doc.org/core-1.9.2/Time.html#method-i-strftime
# %o yields the ordinal representation of the day
date_format: "ordinal"
kramdown:
  input: GFM
  auto_ids:       false
  footnote_nr:    1
  entity_output:  as_char
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  parse_block_html: true

highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-time-to-read
  - octopress-include-tag

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
